- id: buf-format
  name: buf-format
  description: Runs buf format
  types: [proto]
  language: script
  entry: buf-exec.sh format

- id: buf-lint
  name: buf-lint
  description: Runs buf lint
  types: [proto]
  language: script
  entry: buf-exec.sh lint
